# Generated by Django 6.0.2 on 2026-03-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('CocaCola', 'Coca Cola'), ('Sprite', 'Sprite'), ('Fanta', 'Fanta'), ('ThumbsUp', 'Thumbs Up'), ('Limca', 'Limca'), ('Kinley', 'Kinley')], max_length=50)),
                ('bottle_size', models.CharField(choices=[('200ml', '200ml'), ('300ml', '300ml'), ('600ml', '600ml'), ('1L', '1 Liter'), ('2L', '2 Liter')], max_length=20)),
                ('crate_size', models.IntegerField(help_text='Number of bottles per crate')),
                ('rate_per_bottle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
