# Generated by Django 4.2.7 on 2026-04-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('CocaCola', 'Coca Cola'), ('Sprite', 'Sprite'), ('Fanta', 'Fanta'), ('ThumbsUp', 'Thumbs Up'), ('Limca', 'Limca'), ('Kinley', 'Kinley'), ('Pepsi', 'Pepsi'), ('MirindaOrange', 'Mirinda Orange'), ('MirindaLemon', 'Mirinda Lemon'), ('7Up', '7Up'), ('MountainDew', 'Mountain Dew'), ('Slice', 'Slice'), ('Frooti', 'Frooti'), ('Maaza', 'Maaza'), ('RealJuice', 'Real Juice'), ('TropicanaOrange', 'Tropicana Orange'), ('TropicanaApple', 'Tropicana Apple'), ('TropicanaGuava', 'Tropicana Guava'), ('Appy', 'Appy Fizz'), ('AppyClassic', 'Appy Classic'), ('RedBull', 'Red Bull'), ('Monster', 'Monster Energy'), ('Sting', 'Sting Energy'), ('CloudyLemon', 'Cloudy Lemon'), ('Nimbooz', 'Nimbooz'), ('NimboozMasala', 'Nimbooz Masala Soda'), ('Minute', 'Minute Maid'), ('MinutePulpy', 'Minute Maid Pulpy Orange'), ('Aquafina', 'Aquafina Water'), ('Bailley', 'Bailley Water'), ('KinleyWater', 'Kinley Water'), ('BisleriSoda', 'Bisleri Soda'), ('EvervessLemon', 'Evervess Lemon'), ('EvervessSoda', 'Evervess Soda'), ('GoldSpot', 'Gold Spot'), ('Campa', 'Campa Cola'), ('CampaOrange', 'Campa Orange'), ('CampaLemon', 'Campa Lemon'), ('ThumsUpCharged', 'Thums Up Charged'), ('CokeZero', 'Coca-Cola Zero'), ('DietCoke', 'Diet Coke'), ('SpriteLemon', 'Sprite Lemon'), ('FantaGreen', 'Fanta Green Apple'), ('FantaStrawberry', 'Fanta Strawberry'), ('PepsiBlack', 'Pepsi Black'), ('PepsiMango', 'Pepsi Mango'), ('Lipton', 'Lipton Ice Tea'), ('FuzeIceTea', 'Fuze Ice Tea'), ('Gatorade', 'Gatorade'), ('PoweradeBlue', 'Powerade Blue')], max_length=50),
        ),
    ]
