# Generated by Django 4.2.7 on 2026-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('CocaCola', 'Coca Cola'), ('Sprite', 'Sprite'), ('Fanta', 'Fanta'), ('ThumbsUp', 'Thumbs Up'), ('Limca', 'Limca'), ('Kinley', 'Kinley')], max_length=50),
        ),
    ]
