# Generated by Django 4.2.7 on 2026-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottle_size',
            field=models.CharField(choices=[('125ml', '125ml'), ('150ml', '150ml'), ('200ml', '200ml'), ('250ml', '250ml'), ('300ml', '300ml'), ('500ml', '500ml'), ('600ml', '600ml'), ('750ml', '750ml'), ('1L', '1 Liter'), ('1.25L', '1.25 Liter'), ('1.5L', '1.5 Liter'), ('1.75L', '1.75 Liter'), ('2L', '2 Liter'), ('2.25L', '2.25 Liter'), ('2.5L', '2.5 Liter')], max_length=20),
        ),
    ]
