# Generated by Django 4.2.7 on 2026-04-14 06:15

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_bottle_size_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(validators=[apps.products.models.validate_future_date]),
        ),
    ]
