# Generated by Django 6.0.1 on 2026-03-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_actual_delivery_order_delivery_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
