# Generated by Django 6.0.1 on 2026-03-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_driver_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_number', models.CharField(blank=True, help_text='e.g. MH 12 AB 1234', max_length=50, null=True)),
                ('vehicle_type', models.CharField(blank=True, help_text='e.g. Tempo, Bike, Auto', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Driver',
                'verbose_name_plural': 'Delivery Drivers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_driver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Select from saved drivers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliverydriver'),
        ),
    ]
