# Generated by Django 6.0.1 on 2026-03-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
