# Generated by Django 6.0.1 on 2026-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='9960991017@ybl', help_text='e.g. 9960991017@ybl', max_length=100)),
                ('upi_name', models.CharField(default='Shree Ganesh Agency', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='State Bank of India', max_length=100)),
                ('qr_image', models.ImageField(blank=True, help_text='Upload your PhonePe / GPay / Paytm QR code image', null=True, upload_to='upi_qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UPI Configuration',
                'verbose_name_plural': 'UPI Configuration',
            },
        ),
    ]
