# Generated by Django 6.0.1 on 2026-03-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_user'),
        ('orders', '0002_order_actual_delivery_order_delivery_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Damaged', 'Damaged / Broken'), ('Wrong Item', 'Wrong Item Delivered'), ('Excess Delivery', 'Excess Delivery'), ('Quality Issue', 'Quality Issue'), ('Other', 'Other')], max_length=50)),
                ('return_type', models.CharField(choices=[('Return', 'Product Return'), ('Refund', 'Cash Refund'), ('Credit', 'Credit Adjustment')], default='Return', max_length=20)),
                ('quantity_crates', models.IntegerField(default=0)),
                ('quantity_bottles', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
