# Generated by Django 6.0.1 on 2026-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('payment_reminder', 'Payment Reminder'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock Alert'), ('new_order_admin', 'New Order (Admin)'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
