# Generated by Django 4.2.7 on 2026-04-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🎁', max_length=10)),
                ('accent', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('gold', 'Gold'), ('orange', 'Orange'), ('purple', 'Purple'), ('green', 'Green')], default='gold', max_length=20)),
                ('expires_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Special Offer',
                'verbose_name_plural': 'Special Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
