# Generated by Django 4.2.7 on 2026-04-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_out_for_delivery', 'Out for Delivery'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_reminder', 'Payment Reminder'), ('payment_received', 'Payment Received'), ('low_stock', 'Low Stock Alert'), ('new_order_admin', 'New Order (Admin)'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
